### PR TITLE
Load ann miner settings from config file

### PR DESCRIPTION
**Pull request by 3rror404**
Allows some or all of the ann miner settings to be loaded via a JSON file. 

Provide either a path to a local file or a URL to a web-accessible file/API in the `--config` CLI argument. 

```
./target/release/packetcrypt ann --config "/path/to/config.json"
```
Or
```
./target/release/packetcrypt ann --config https://example.com/config.json

```

A config.json file can be generated here for testing: https://config.pkt.watch

---

I’m a Rust novice. I’m not 100% confident with the code. So feel free to point out anything that looks poor/wrong and I’ll try to fix it.

### CODE REVIEW

**Review by Frank-Buss — COMMENTED** [review]
I'm note sure if it is a good idea to request specifically serde 1.0.136 (and the same for serde_json). This would prohibit bug fixes, because the last number are API compatible changes and only bug fixes.

I think the Rust philosophy is to update Cargo.lock before a new release is done (just deleting it before building should be sufficient), and then committing the new Cargo.lock file, so that creating the same release uses the same (probably tested) and locked library versions.

In theory, after an update of the Cargo.lock file, every new version of every library used, should be checked, to avoid disasters like known from NodeJS. But this is outside the scope of this project and a general problem. Might be sufficient to test a new version with all libraries updated on a VM before releasing it, to check nothing obviously bad is happening.

**Comment by cjdelisle** [comment]
Agree, better put serde / serde_json at 1.0 and let bug fixes happen from time to time. Of course I would update just *after* a release rather than before, but it's the same idea.

**Comment by 3rror404** [comment]
Thanks guys. My understanding was that only the left most number is pegged. So using 1.0.136 would allow any versions >=1.0.136 &  < 2.0.0. Am I reading this incorrectly?

> The string "0.1.12" is a version requirement. Although it looks like a specific version of the time crate, it actually specifies a range of versions and allows [SemVer](https://semver.org/) compatible updates. An update is allowed if the new version number does not modify the left-most non-zero digit in the major, minor, patch grouping

https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#specifying-dependencies-from-cratesio

**Comment by Frank-Buss** [comment]
Interesting, didn't know this, this doesn't look very intuitive :-) But maybe still better to just use 1.0, unless you need at least 1.0.136.

**Comment by 3rror404** [comment]
Just testing now. I don't think 1.0.136 is necessary - I only used that version because it was used in the snippet on crates.io.

**Comment by rsalmei** [comment]
Out of curiosity, cargo does use some unintuitive SemVer ranges. The one we grow to expect would be the [tilde requirements](https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#tilde-requirements) which is not much used. There are special cases for "0.x.x" versions, which are deemed not stable yet, and also for "1.x.x" ones.

**Pull request merged**
